# More info on config here: https://golangci-lint.run/usage/configuration/#config-file
run:
  timeout: 10m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - bin
    - vendor
    - var
    - tmp
  skip-files:
    - \_mock.go
    - \.pb\.go$
    - \.pb\.gw\.go$

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  govet:
    check-shadowing: true
  dupl:
    threshold: 100
  goconst:
    min-len:         2
    min-occurrences: 2

linters:
  disable-all: true
  enable:
    - errcheck
    #- goconst
    - goimports
    - gosec
    - govet
    - ineffassign
    #- revive

issues:
  exclude-use-default: false
  exclude:
    - G102
    - should have a package comment, unless it's in another file for this package
    - should have comment
    - comment on exported
    - should be `URLID`
