services:
  postgres:
    image: postgres:14.4
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tasks
    container_name: 'postgres-tasks'
    volumes:
      - postgres-data:/var/lib/postgresql/data # том для того, чтобы при перезапуске контейнера все данные сохранялись
      - ./docker/postgres/postgres.conf:/etc/postgresql/postgresql.conf # конфиг БД
      - ./docker/postgres/testing-db.sql:/docker-entrypoint-initdb.d/testing-db.sql
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    ports:
      - 5432:5432
    restart: always

volumes:
  postgres-data: